import Link from 'next/link'
import { Button, PageHeader } from '@beaconhs/ui'
import { can } from '@beaconhs/tenant'
import { requireRequestContext } from '@/lib/auth'
import { getDiaryOccurrenceDetail, isOperationalTaskOverdue } from '@/lib/hospitality/diary'
import { createDiaryCorrectiveActionAction } from '../../actions'

const labels: Record<string, string> = { upcoming_reminder: 'Reminder sent', due_notification: 'Due notification sent', overdue_notification: 'Overdue notification sent', manager_notification: 'Manager notified', escalated: 'Escalated' }

export default async function DiaryTaskPage({ params }: { params: Promise<{ propertyId: string; occurrenceId: string }> }) {
  const ctx = await requireRequestContext(); const { propertyId, occurrenceId } = await params
  const task = await getDiaryOccurrenceDetail(ctx, propertyId, occurrenceId); const overdue = isOperationalTaskOverdue(task.occurrence)
  const manage = can(ctx, 'hospitality.manage')
  return <main className="mx-auto max-w-3xl p-4 sm:p-6"><PageHeader title={task.template.title} description={`${task.occurrence.status} · due ${task.occurrence.dueAt.toLocaleString()}`} action={<Button asChild variant="outline"><Link href={`/hospitality/properties/${propertyId}/diary`}>Back to diary</Link></Button>}/><section className="mt-5 rounded-lg border p-4"><p>{task.template.instructions || 'No instructions provided.'}</p><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">Scheduled</dt><dd>{task.occurrence.occurrenceAt.toLocaleString()}</dd></div><div><dt className="text-muted-foreground">Due</dt><dd>{task.occurrence.dueAt.toLocaleString()}</dd></div><div><dt className="text-muted-foreground">Timezone</dt><dd>{task.schedule.timezone}</dd></div><div><dt className="text-muted-foreground">Overdue</dt><dd>{overdue ? `${Math.floor((Date.now()-task.occurrence.dueAt.getTime())/3600000)} hours` : 'No'}</dd></div><div><dt className="text-muted-foreground">Completed</dt><dd>{task.occurrence.completedAt?.toLocaleString() ?? 'Not completed'}</dd></div><div><dt className="text-muted-foreground">Completion notes</dt><dd>{task.occurrence.completionNotes ?? '—'}</dd></div></dl></section><section className="mt-5 rounded-lg border p-4"><h2 className="font-semibold">Lifecycle history</h2><ol className="mt-3 space-y-2 text-sm">{task.events.length ? task.events.map((event) => <li key={event.id}>{labels[event.stage] ?? event.stage} <span className="text-muted-foreground">· {event.processedAt.toLocaleString()}</span></li>) : <li className="text-muted-foreground">No lifecycle events yet.</li>}</ol></section><section className="mt-5 rounded-lg border p-4"><h2 className="font-semibold">Corrective action</h2>{task.correctiveAction ? <p className="mt-2"><Link className="underline" href={`/corrective-actions/${task.correctiveAction.id}`}>{task.correctiveAction.reference} · {task.correctiveAction.title} ({task.correctiveAction.status})</Link></p> : manage && overdue ? <form action={createDiaryCorrectiveActionAction} className="mt-3"><input type="hidden" name="propertyId" value={propertyId}/><input type="hidden" name="occurrenceId" value={occurrenceId}/><Button>Create Corrective Action</Button></form> : <p className="mt-2 text-sm text-muted-foreground">No corrective action linked.</p>}</section></main>
}
