-- Additive Uvanoo hospitality operational foundation. Existing construction
-- org_units and equipment_work_orders remain unchanged.
CREATE TYPE "hospitality_room_status" AS ENUM ('available','occupied','out_of_service','maintenance','blocked');
CREATE TYPE "qr_target_kind" AS ENUM ('room','asset');
CREATE TYPE "maintenance_issue_status" AS ENUM ('reported','triaged','work_ordered','cancelled');
CREATE TYPE "maintenance_work_order_status" AS ENUM ('open','assigned','in_progress','awaiting_parts','completed','verified','closed','cancelled');
CREATE TYPE "operational_task_status" AS ENUM ('open','in_progress','completed','overdue','escalated','waived','cancelled');
CREATE TYPE "manager_signoff_kind" AS ENUM ('weekly','monthly');
CREATE TYPE "tenant_module_entitlement_state" AS ENUM ('enabled','disabled');

CREATE TABLE "hospitality_properties" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"tenant_id" uuid NOT NULL,"name" text NOT NULL,"code" text NOT NULL,"timezone" text NOT NULL,"address" jsonb DEFAULT '{}'::jsonb NOT NULL,"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL,"deleted_at" timestamptz, CONSTRAINT "hospitality_properties_tenant_fk" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE cascade);
CREATE UNIQUE INDEX "hospitality_properties_tenant_code_ux" ON "hospitality_properties" ("tenant_id","code");
CREATE UNIQUE INDEX "hospitality_properties_tenant_id_id_ux" ON "hospitality_properties" ("tenant_id","id");
CREATE TABLE "hospitality_buildings" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"tenant_id" uuid NOT NULL,"property_id" uuid NOT NULL,"name" text NOT NULL,"code" text NOT NULL,"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL,"deleted_at" timestamptz, CONSTRAINT "hospitality_buildings_tenant_property_fk" FOREIGN KEY ("tenant_id","property_id") REFERENCES "hospitality_properties"("tenant_id","id") ON DELETE cascade);
CREATE UNIQUE INDEX "hospitality_buildings_property_code_ux" ON "hospitality_buildings" ("tenant_id","property_id","code");
CREATE UNIQUE INDEX "hospitality_buildings_tenant_id_id_ux" ON "hospitality_buildings" ("tenant_id","id");
CREATE TABLE "hospitality_floors" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"tenant_id" uuid NOT NULL,"building_id" uuid NOT NULL,"name" text NOT NULL,"code" text NOT NULL,"sort_order" text DEFAULT '0' NOT NULL,"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL,"deleted_at" timestamptz, CONSTRAINT "hospitality_floors_tenant_building_fk" FOREIGN KEY ("tenant_id","building_id") REFERENCES "hospitality_buildings"("tenant_id","id") ON DELETE cascade);
CREATE UNIQUE INDEX "hospitality_floors_building_code_ux" ON "hospitality_floors" ("tenant_id","building_id","code");
CREATE UNIQUE INDEX "hospitality_floors_tenant_id_id_ux" ON "hospitality_floors" ("tenant_id","id");
CREATE TABLE "hospitality_rooms" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"tenant_id" uuid NOT NULL,"floor_id" uuid NOT NULL,"code" text NOT NULL,"name" text,"room_type" text,"status" "hospitality_room_status" DEFAULT 'available' NOT NULL,"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL,"deleted_at" timestamptz, CONSTRAINT "hospitality_rooms_tenant_floor_fk" FOREIGN KEY ("tenant_id","floor_id") REFERENCES "hospitality_floors"("tenant_id","id") ON DELETE cascade);
CREATE UNIQUE INDEX "hospitality_rooms_tenant_code_ux" ON "hospitality_rooms" ("tenant_id","code");
CREATE UNIQUE INDEX "hospitality_rooms_tenant_id_id_ux" ON "hospitality_rooms" ("tenant_id","id");
CREATE TABLE "qr_targets" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"tenant_id" uuid NOT NULL,"token" text NOT NULL,"kind" "qr_target_kind" NOT NULL,"room_id" uuid,"equipment_item_id" uuid,"is_active" boolean DEFAULT true NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "qr_targets_exactly_one_target_ck" CHECK ((room_id IS NOT NULL)::int + (equipment_item_id IS NOT NULL)::int = 1), CONSTRAINT "qr_targets_tenant_room_fk" FOREIGN KEY ("tenant_id","room_id") REFERENCES "hospitality_rooms"("tenant_id","id"), CONSTRAINT "qr_targets_tenant_equipment_fk" FOREIGN KEY ("tenant_id","equipment_item_id") REFERENCES "equipment_items"("tenant_id","id"));
CREATE UNIQUE INDEX "qr_targets_token_ux" ON "qr_targets" ("token");
CREATE UNIQUE INDEX "qr_targets_room_ux" ON "qr_targets" ("tenant_id","room_id");
CREATE TABLE "maintenance_issues" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"tenant_id" uuid NOT NULL,"room_id" uuid,"equipment_item_id" uuid,"reference" text NOT NULL,"status" "maintenance_issue_status" DEFAULT 'reported' NOT NULL,"priority" text DEFAULT 'medium' NOT NULL,"summary" text NOT NULL,"description" text,"reported_by_tenant_user_id" uuid,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "maintenance_issues_exactly_one_target_ck" CHECK ((room_id IS NOT NULL)::int + (equipment_item_id IS NOT NULL)::int = 1), CONSTRAINT "maintenance_issues_tenant_room_fk" FOREIGN KEY ("tenant_id","room_id") REFERENCES "hospitality_rooms"("tenant_id","id"), CONSTRAINT "maintenance_issues_tenant_equipment_fk" FOREIGN KEY ("tenant_id","equipment_item_id") REFERENCES "equipment_items"("tenant_id","id"), CONSTRAINT "maintenance_issues_tenant_reporter_fk" FOREIGN KEY ("tenant_id","reported_by_tenant_user_id") REFERENCES "tenant_users"("tenant_id","id"));
CREATE UNIQUE INDEX "maintenance_issues_tenant_reference_ux" ON "maintenance_issues" ("tenant_id","reference");
CREATE UNIQUE INDEX "maintenance_issues_tenant_id_id_ux" ON "maintenance_issues" ("tenant_id","id");
CREATE TABLE "maintenance_work_orders" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"tenant_id" uuid NOT NULL,"issue_id" uuid NOT NULL,"reference" text NOT NULL,"status" "maintenance_work_order_status" DEFAULT 'open' NOT NULL,"assigned_to_tenant_user_id" uuid,"verified_by_tenant_user_id" uuid,"completed_at" timestamptz,"verified_at" timestamptz,"closed_at" timestamptz,"action_taken" text,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "maintenance_work_orders_tenant_issue_fk" FOREIGN KEY ("tenant_id","issue_id") REFERENCES "maintenance_issues"("tenant_id","id") ON DELETE cascade);
CREATE UNIQUE INDEX "maintenance_work_orders_tenant_reference_ux" ON "maintenance_work_orders" ("tenant_id","reference");
CREATE UNIQUE INDEX "maintenance_work_orders_issue_ux" ON "maintenance_work_orders" ("tenant_id","issue_id");
CREATE TABLE "operational_task_templates" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"tenant_id" uuid NOT NULL,"title" text NOT NULL,"instructions" text,"requires_evidence" boolean DEFAULT false NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL,"deleted_at" timestamptz, CONSTRAINT "operational_task_templates_tenant_fk" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE cascade);
CREATE TABLE "operational_task_schedules" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"tenant_id" uuid NOT NULL,"template_id" uuid NOT NULL,"property_id" uuid NOT NULL,"timezone" text NOT NULL,"recurrence" jsonb NOT NULL,"starts_at" timestamptz NOT NULL,"is_active" boolean DEFAULT true NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "operational_task_schedules_tenant_template_fk" FOREIGN KEY ("tenant_id","template_id") REFERENCES "operational_task_templates"("tenant_id","id"), CONSTRAINT "operational_task_schedules_tenant_property_fk" FOREIGN KEY ("tenant_id","property_id") REFERENCES "hospitality_properties"("tenant_id","id"));
CREATE TABLE "operational_task_occurrences" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"tenant_id" uuid NOT NULL,"schedule_id" uuid NOT NULL,"occurrence_at" timestamptz NOT NULL,"due_at" timestamptz NOT NULL,"status" "operational_task_status" DEFAULT 'open' NOT NULL,"assigned_to_tenant_user_id" uuid,"completed_at" timestamptz,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "operational_task_occurrences_tenant_schedule_fk" FOREIGN KEY ("tenant_id","schedule_id") REFERENCES "operational_task_schedules"("tenant_id","id") ON DELETE cascade);
CREATE UNIQUE INDEX "operational_task_occurrences_schedule_occurrence_ux" ON "operational_task_occurrences" ("tenant_id","schedule_id","occurrence_at");
CREATE TABLE "manager_signoffs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"tenant_id" uuid NOT NULL,"property_id" uuid NOT NULL,"kind" "manager_signoff_kind" NOT NULL,"period_start" timestamptz NOT NULL,"period_end" timestamptz NOT NULL,"summary" jsonb NOT NULL,"comments" text,"confirmed_at" timestamptz NOT NULL,"confirmed_by_tenant_user_id" uuid NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "manager_signoffs_tenant_property_fk" FOREIGN KEY ("tenant_id","property_id") REFERENCES "hospitality_properties"("tenant_id","id"), CONSTRAINT "manager_signoffs_tenant_confirmer_fk" FOREIGN KEY ("tenant_id","confirmed_by_tenant_user_id") REFERENCES "tenant_users"("tenant_id","id"));
CREATE UNIQUE INDEX "manager_signoffs_period_ux" ON "manager_signoffs" ("tenant_id","property_id","kind","period_start","period_end");
CREATE TABLE "tenant_module_entitlements" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"tenant_id" uuid NOT NULL,"module_key" text NOT NULL,"state" "tenant_module_entitlement_state" DEFAULT 'enabled' NOT NULL,"effective_from" timestamptz,"effective_until" timestamptz,"changed_by_user_id" text,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "tenant_module_entitlements_tenant_fk" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE cascade);
CREATE UNIQUE INDEX "tenant_module_entitlements_tenant_module_ux" ON "tenant_module_entitlements" ("tenant_id","module_key");
